/**
 * Domain model for the 3-system architecture (see AI-PRD.md):
 *   System 1  — per-review tagging        (ReviewTag)
 *   System 2  — aggregation + prevalence  (SkuAggregate, IssueStat)
 *   System 2.5— agentic diagnosis         (Diagnosis)
 *   System 3  — decision + gate           (Decision)
 *
 * This is additive to the legacy `types.ts` — the new pipeline lives beside the old
 * one until the swap, so `npm run build` stays green throughout the migration.
 */

// ─────────────────────────────────────────────────────────────────────────────
// Shared
// ─────────────────────────────────────────────────────────────────────────────

export type Band = "low" | "medium" | "high";

/** Closed problem taxonomy + explicit escape hatch. Maps 1:1 to the §3 policy table. */
export type ProblemClass =
  | "time"
  | "partner_attitude"
  | "skill_issue"
  | "undisclosed_supplies"
  | "unfair_review"
  | "pricing"
  | "out_of_taxonomy";

export const PROBLEM_CLASSES: ProblemClass[] = [
  "time",
  "partner_attitude",
  "skill_issue",
  "undisclosed_supplies",
  "unfair_review",
  "pricing",
  "out_of_taxonomy",
];

/** `unimprovable` is a derived System-3 state, never a review tag. */
export type RootCause = ProblemClass | "unimprovable";

/** Grave subtypes → immediate platform pause; hygiene (lesser) → needs 2nd corroborating signal. */
export type SafetySubtype = "injury" | "harassment" | "theft" | "hygiene";
export const GRAVE_SAFETY: SafetySubtype[] = ["injury", "harassment", "theft"];
export const isGraveSafety = (s: SafetySubtype | null): boolean =>
  s !== null && GRAVE_SAFETY.includes(s);

// ─────────────────────────────────────────────────────────────────────────────
// Customers & reviews (inputs)
// ─────────────────────────────────────────────────────────────────────────────

export interface Customer {
  id: string;
  karma: number; // 0..1 reviewer-trust score (joined input, never generated by the tagger)
  aovBand: Band; // blended cross-category AoV band
  ltvBand: Band; // informational
}

export interface Review {
  id: string;
  partnerId: string;
  customerId: string;
  sku: string;
  rating: 1 | 2 | 3 | 4 | 5;
  text: string;
  date: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// System 1 — Review Tagging
// ─────────────────────────────────────────────────────────────────────────────

export type Sentiment = "positive" | "neutral" | "negative";
export type Target = "partner" | "urban_company" | "pricing" | "customer_self" | "irrelevant";

export type TagFlag =
  | "out_of_taxonomy"
  | "injection_quarantined"
  | "thin_text"
  | "non_verbatim"
  | "low_trust_reviewer"
  | "needs_human";

export interface CustomerContext {
  karma: number;
  aovBand: Band;
  ltvBand: Band;
  /** aovBand === "high" && karma >= KARMA_GOOD — complaint up-weighted + surfaced in the high-value tab. */
  highValue: boolean;
}

export interface ReviewTag {
  reviewId: string;
  partnerId: string;
  sku: string;
  sentiment: Sentiment;
  target: Target;
  problemClasses: ProblemClass[];
  severity: number; // 1..5; safety-critical forces >= 4
  safetyFlag: boolean;
  safetySubtype: SafetySubtype | null; // present iff safetyFlag
  evidenceQuotes: string[]; // verbatim spans, required if negative
  customer: CustomerContext;
  confidence: number; // 0..1
  flags: TagFlag[];
}

// ─────────────────────────────────────────────────────────────────────────────
// System 2 — Aggregation + prevalence gate
// ─────────────────────────────────────────────────────────────────────────────

export interface IssueStat {
  problemClass: ProblemClass;
  rawComplaints: number;
  weightedComplaints: number; // karma / high-value weighted
  issueRate: number; // weightedComplaints ÷ bookingsCount — the prevalence signal
  severityP50: number;
  severityMax: number;
  /** Cleared ISSUE_PREVALENCE_THRESHOLD (severity-scaled) AND the min-complaints floor. */
  actionable: boolean;
}

export interface SkuAggregate {
  partnerId: string;
  sku: string;
  zone: string;
  bookingsCount: number; // THIS partner's bookings for THIS sku in the window — the denominator
  reviewCount: number;
  avgRating: number;
  issues: IssueStat[];
  problemMix: Partial<Record<ProblemClass, number>>; // share among complaints — NOT the trigger
  safetyGraveCount: number;
  safetyLesserCount: number;
  safetyQuotes: string[]; // verbatim quotes from the safety-flagged reviews ("evidence or silence")
  highValueComplaints: number; // negative complaints from high-value (trusted, high-AoV) customers
  lowTrustComplaints: number; // negative complaints from low-trust reviewers (down-weighted)
  cohortPctile: number; // vs same sku × zone peers (0..1)
  lowN: boolean; // reviewCount < MIN_REVIEWS
}

// ─────────────────────────────────────────────────────────────────────────────
// System 2.5 — Diagnosis
// ─────────────────────────────────────────────────────────────────────────────

export type DiagnosisFlag = "insufficient_evidence" | "conflicting_signal" | "needs_human";

export interface Diagnosis {
  partnerId: string;
  sku: string;
  primaryCause: RootCause;
  significantCauses: ProblemClass[]; // all above-bar causes → parallel interventions (MULTI_CAUSE)
  evidenceQuotes: string[];
  confidence: number; // GATING confidence
  alternativesConsidered: string[];
  reasoning: string;
  flags: DiagnosisFlag[];
  evidenceValid: boolean;
}

// ─────────────────────────────────────────────────────────────────────────────
// System 3 — Decision + gate
// ─────────────────────────────────────────────────────────────────────────────

export type SeverityTrack = "safety" | "accelerated" | "standard";

export type BanGrain = "per_sku" | "platform";

export type ActionKind =
  | "do_nothing"
  | "skill_training"
  | "warning_scrutiny"
  | "supply_kit"
  | "review_protection"
  | "protective_soft_ban" // concurrent per-SKU soft-ban on the accelerated track
  | "soft_ban"
  | "hard_ban"
  | "offboard"
  | "safety_pause";

export type GateRoute = "auto_approved" | "human_required" | "held_for_corroboration";

export interface Decision {
  partnerId: string;
  sku: string;
  cause: RootCause | "none";
  track: SeverityTrack;
  actions: ActionKind[]; // may be several — parallel interventions for a multi-cause partner
  /**
   * Executed immediately, before any human review — only ever the reversible precautionary
   * safety_pause (grave or corroborated-lesser safety). The gated decision (offboard vs
   * exonerate) stays in `actions` behind the human gate.
   */
  immediateActions: ActionKind[];
  incomeAffecting: boolean;
  grain: BanGrain | null; // per-SKU for numeric severity; platform only for a safety_flag
  gate: GateRoute;
  gateReason: string;
  evidenceQuotes: string[];
}

/**
 * Per partner × SKU escalation-ladder state (PRD §1b), derived deterministically from the
 * intervention history in the data — never a model output. v0 holds state in-run only.
 */
export interface LadderState {
  coachingCycles: number; // completed coaching interventions (training / warning / supply kit)
  softBanStrikes: number; // soft-bans within the rolling SOFTBAN_WINDOW_DAYS
  daysSinceLastSoftBan: number | null; // null = never soft-banned
  stillFailing: boolean; // monitor scored the latest intervention as stalled (volume floor met)
}

export const NO_LADDER_HISTORY: LadderState = {
  coachingCycles: 0,
  softBanStrikes: 0,
  daysSinceLastSoftBan: null,
  stillFailing: false,
};

// ─────────────────────────────────────────────────────────────────────────────
// Decision-support detail — everything a human needs on one screen to make a
// confident call. Attached per Sku case; derived, never a model output.
// ─────────────────────────────────────────────────────────────────────────────

/** One 7-day bucket of the decision window: counted complaints out of bookings. */
export interface WeekBucket {
  label: string; // short date of the week, e.g. "29 Jun"
  bookings: number; // distinct orders this partner served for this SKU that week
  complaints: number; // partner-attributable complaints that week
  rate: number; // complaints ÷ bookings
}

/** A single counted complaint the decision maker can read verbatim. */
export interface CaseReview {
  date: string;
  rating: number;
  text: string;
  problemClasses: ProblemClass[];
  safetySubtype: SafetySubtype | null; // present iff this is a safety event
  severity: number;
  highValue: boolean;
  lowTrust: boolean;
  weight: number; // how much this review counted (karma / high-value weighting)
}

/** Reviews present for this SKU that were NOT counted against the partner (relevance/quality gate). */
export interface ExcludedSummary {
  offTarget: number; // pricing / app / customer-self — not about the partner
  lowSignal: number; // thin (rating-only) or neutral (3★) — no usable complaint
  quarantined: number; // prompt-injection attempts — blocked, never read as instructions
}

// ─────────────────────────────────────────────────────────────────────────────
// Progress tracking — partners partway through an intervention (across weekly runs)
// ─────────────────────────────────────────────────────────────────────────────

export type ProgressStatus = "recovered" | "improving" | "on_track" | "stalled";

export interface Progress {
  partnerId: string;
  name: string;
  zone: string;
  sku: string;
  interventionLabel: string;
  phase: string; // "Coaching — cycle 1/2", "Soft-ban + coaching", "Recovered", "Stalled — escalating"
  daysElapsed: number;
  windowDays: number; // the 60-day monitor window
  preRate: number; // complaint rate before the intervention
  currentRate: number; // complaint rate now
  dropPct: number; // reduction vs pre (target is 20%)
  targetDrop: number;
  status: ProgressStatus;
  nextCheckDays: number;
  note: string;
  /** Plain-language intervention mix in play — e.g. "Free training", "Warning + watch (no training)", "7-day pause · strike 3/3 + training". */
  interventionSummary: string;
  /** Weekly issue-complaint rate + what happened that week (for the chart + the week-by-week log). `paused` weeks are 7-day soft-bans — no bookings. `event` = the intervention that landed that week. */
  series: { label: string; rate: number; paused?: boolean; bookings: number; complaints: number; event?: string }[];
  /** Index into `series` of the LATEST intervention — the 15-day pre/post scoring anchor + "latest action" tick. */
  interventionWeek: number;
  /** Index into `series` where monitoring began — the FIRST intervention (the "watch started" marker). */
  watchStartWeek: number;
}
